type MEDIA_GROUP_UPLOAD_STATUS =
  | 'COMPLETED'
  | 'FAILED'
  | 'IN_PROGRESS'
  | 'CANCELLED';
type MEDIA_UPLOAD_STATUS =
  | 'COMPLETED'
  | 'FAILED'
  | 'IN_PROGRESS'
  | 'ENCODING'
  | 'CANCELLED';
