import {
  Advertise,
  CrossIcon,
  CustomServices,
  DeclinedStatus,
  DigitalDownload,
  LogoFacebook,
  LogoInstagram,
  LogoOnlyFans,
  LogoSnapChat,
  LogoTikTok,
  LogoTwitter,
  LogoYoutube,
  Payma,
  PendingStatus,
  PopChat,
  PopLive,
  PopSnap,
  Shoutout,
  TickIcon,
} from 'assets/svgs';
import Badget from 'components/badget';
import { OrderStatus, SocialPlatforms, SupportTicketStatus } from 'enums';

export const defaultTags = [
  { label: 'Artist', value: 'artist', selected: false },
  { label: 'Model', value: 'model', selected: false },
  { label: 'Entertainer', value: 'entertainer', selected: false },
  { label: 'Musician', value: 'musician', selected: false },
  { label: 'Coach', value: 'coach', selected: false },
  { label: 'Educator', value: 'educator', selected: false },
  { label: 'Author', value: 'author', selected: false },
  { label: 'Influencer', value: 'influencer', selected: false },
  { label: 'Athlete', value: 'athlete', selected: false },
  { label: 'Gamer', value: 'gamer', selected: false },
  { label: 'Actor', value: 'actor', selected: false },
  { label: 'Other', value: 'other', selected: false },
];

export const LinkTypeName = {
  simpleLink: 'Link',
  sectionTitle: 'Section Title',
  biography: 'Biography',
  youtubeLink: 'Video',
  contentBlock: 'Content Block',
  shoutout: 'Custom Video',
  advertise: 'Promotional Shoutouts',
  payma: 'Paid Q&A',
  poplive: 'Pop Live',
  'additional-services': 'Additional Services',
  'digital-download': 'Digital Download',
  'chat-subscription': 'Chat subscription',
};

export const initialPallet = [
  { offset: '0.00', color: 'rgb(63, 81, 181)', opacity: 1, id: 1 },
  { offset: '1.00', color: 'rgb(255, 255, 255)', opacity: 1, id: 2 },
];

export const socialLinksPrefix = [
  {
    type: 'instagram',
    platformUrl: 'https://www.instagram.com/',
  },
  {
    type: 'tiktok',
    platformUrl: 'https://www.tiktok.com/',
  },
  {
    type: 'twitter',
    platformUrl: 'https://www.twitter.com/',
  },
  {
    type: 'youtube',
    platformUrl: 'https://www.youtube.com/c/',
  },
  {
    type: 'facebook',
    platformUrl: 'https://www.facebook.com/',
  },
  {
    type: 'snapchat',
    platformUrl: 'https://www.snapchat.com/add/',
  },
];

export const timezones = [
  'Africa/Abidjan',
  'Africa/Accra',
  'Africa/Addis_Ababa',
  'Africa/Algiers',
  'Africa/Asmara',
  'Africa/Asmera',
  'Africa/Bamako',
  'Africa/Bangui',
  'Africa/Banjul',
  'Africa/Bissau',
  'Africa/Blantyre',
  'Africa/Brazzaville',
  'Africa/Bujumbura',
  'Africa/Cairo',
  'Africa/Casablanca',
  'Africa/Ceuta',
  'Africa/Conakry',
  'Africa/Dakar',
  'Africa/Dar_es_Salaam',
  'Africa/Djibouti',
  'Africa/Douala',
  'Africa/El_Aaiun',
  'Africa/Freetown',
  'Africa/Gaborone',
  'Africa/Harare',
  'Africa/Johannesburg',
  'Africa/Juba',
  'Africa/Kampala',
  'Africa/Khartoum',
  'Africa/Kigali',
  'Africa/Kinshasa',
  'Africa/Lagos',
  'Africa/Libreville',
  'Africa/Lome',
  'Africa/Luanda',
  'Africa/Lubumbashi',
  'Africa/Lusaka',
  'Africa/Malabo',
  'Africa/Maputo',
  'Africa/Maseru',
  'Africa/Mbabane',
  'Africa/Mogadishu',
  'Africa/Monrovia',
  'Africa/Nairobi',
  'Africa/Ndjamena',
  'Africa/Niamey',
  'Africa/Nouakchott',
  'Africa/Ouagadougou',
  'Africa/Porto-Novo',
  'Africa/Sao_Tome',
  'Africa/Timbuktu',
  'Africa/Tripoli',
  'Africa/Tunis',
  'Africa/Windhoek',
  'America/Adak',
  'America/Anchorage',
  'America/Anguilla',
  'America/Antigua',
  'America/Araguaina',
  'America/Argentina/Buenos_Aires',
  'America/Argentina/Catamarca',
  'America/Argentina/ComodRivadavia',
  'America/Argentina/Cordoba',
  'America/Argentina/Jujuy',
  'America/Argentina/La_Rioja',
  'America/Argentina/Mendoza',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Salta',
  'America/Argentina/San_Juan',
  'America/Argentina/San_Luis',
  'America/Argentina/Tucuman',
  'America/Argentina/Ushuaia',
  'America/Aruba',
  'America/Asuncion',
  'America/Atikokan',
  'America/Atka',
  'America/Bahia',
  'America/Bahia_Banderas',
  'America/Barbados',
  'America/Belem',
  'America/Belize',
  'America/Blanc-Sablon',
  'America/Boa_Vista',
  'America/Bogota',
  'America/Boise',
  'America/Buenos_Aires',
  'America/Cambridge_Bay',
  'America/Campo_Grande',
  'America/Cancun',
  'America/Caracas',
  'America/Catamarca',
  'America/Cayenne',
  'America/Cayman',
  'America/Chicago',
  'America/Chihuahua',
  'America/Coral_Harbour',
  'America/Cordoba',
  'America/Costa_Rica',
  'America/Creston',
  'America/Cuiaba',
  'America/Curacao',
  'America/Danmarkshavn',
  'America/Dawson',
  'America/Dawson_Creek',
  'America/Denver',
  'America/Detroit',
  'America/Dominica',
  'America/Edmonton',
  'America/Eirunepe',
  'America/El_Salvador',
  'America/Ensenada',
  'America/Fort_Nelson',
  'America/Fort_Wayne',
  'America/Fortaleza',
  'America/Glace_Bay',
  'America/Godthab',
  'America/Goose_Bay',
  'America/Grand_Turk',
  'America/Grenada',
  'America/Guadeloupe',
  'America/Guatemala',
  'America/Guayaquil',
  'America/Guyana',
  'America/Halifax',
  'America/Havana',
  'America/Hermosillo',
  'America/Indiana/Indianapolis',
  'America/Indiana/Knox',
  'America/Indiana/Marengo',
  'America/Indiana/Petersburg',
  'America/Indiana/Tell_City',
  'America/Indiana/Vevay',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Indianapolis',
  'America/Inuvik',
  'America/Iqaluit',
  'America/Jamaica',
  'America/Jujuy',
  'America/Juneau',
  'America/Kentucky/Louisville',
  'America/Kentucky/Monticello',
  'America/Knox_IN',
  'America/Kralendijk',
  'America/La_Paz',
  'America/Lima',
  'America/Los_Angeles',
  'America/Louisville',
  'America/Lower_Princes',
  'America/Maceio',
  'America/Managua',
  'America/Manaus',
  'America/Marigot',
  'America/Martinique',
  'America/Matamoros',
  'America/Mazatlan',
  'America/Mendoza',
  'America/Menominee',
  'America/Merida',
  'America/Metlakatla',
  'America/Mexico_City',
  'America/Miquelon',
  'America/Moncton',
  'America/Monterrey',
  'America/Montevideo',
  'America/Montreal',
  'America/Montserrat',
  'America/Nassau',
  'America/New_York',
  'America/Nipigon',
  'America/Nome',
  'America/Noronha',
  'America/North_Dakota/Beulah',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'America/Nuuk',
  'America/Ojinaga',
  'America/Panama',
  'America/Pangnirtung',
  'America/Paramaribo',
  'America/Phoenix',
  'America/Port-au-Prince',
  'America/Port_of_Spain',
  'America/Porto_Acre',
  'America/Porto_Velho',
  'America/Puerto_Rico',
  'America/Punta_Arenas',
  'America/Rainy_River',
  'America/Rankin_Inlet',
  'America/Recife',
  'America/Regina',
  'America/Resolute',
  'America/Rio_Branco',
  'America/Rosario',
  'America/Santa_Isabel',
  'America/Santarem',
  'America/Santiago',
  'America/Santo_Domingo',
  'America/Sao_Paulo',
  'America/Scoresbysund',
  'America/Shiprock',
  'America/Sitka',
  'America/St_Barthelemy',
  'America/St_Johns',
  'America/St_Kitts',
  'America/St_Lucia',
  'America/St_Thomas',
  'America/St_Vincent',
  'America/Swift_Current',
  'America/Tegucigalpa',
  'America/Thule',
  'America/Thunder_Bay',
  'America/Tijuana',
  'America/Toronto',
  'America/Tortola',
  'America/Vancouver',
  'America/Virgin',
  'America/Whitehorse',
  'America/Winnipeg',
  'America/Yakutat',
  'America/Yellowknife',
  'Antarctica/Casey',
  'Antarctica/Davis',
  'Antarctica/DumontDUrville',
  'Antarctica/Macquarie',
  'Antarctica/Mawson',
  'Antarctica/McMurdo',
  'Antarctica/Palmer',
  'Antarctica/Rothera',
  'Antarctica/South_Pole',
  'Antarctica/Syowa',
  'Antarctica/Troll',
  'Antarctica/Vostok',
  'Arctic/Longyearbyen',
  'Asia/Aden',
  'Asia/Almaty',
  'Asia/Amman',
  'Asia/Anadyr',
  'Asia/Aqtau',
  'Asia/Aqtobe',
  'Asia/Ashgabat',
  'Asia/Ashkhabad',
  'Asia/Atyrau',
  'Asia/Baghdad',
  'Asia/Bahrain',
  'Asia/Baku',
  'Asia/Bangkok',
  'Asia/Barnaul',
  'Asia/Beirut',
  'Asia/Bishkek',
  'Asia/Brunei',
  'Asia/Calcutta',
  'Asia/Chita',
  'Asia/Choibalsan',
  'Asia/Chongqing',
  'Asia/Chungking',
  'Asia/Colombo',
  'Asia/Dacca',
  'Asia/Damascus',
  'Asia/Dhaka',
  'Asia/Dili',
  'Asia/Dubai',
  'Asia/Dushanbe',
  'Asia/Famagusta',
  'Asia/Gaza',
  'Asia/Harbin',
  'Asia/Hebron',
  'Asia/Ho_Chi_Minh',
  'Asia/Hong_Kong',
  'Asia/Hovd',
  'Asia/Irkutsk',
  'Asia/Istanbul',
  'Asia/Jakarta',
  'Asia/Jayapura',
  'Asia/Jerusalem',
  'Asia/Kabul',
  'Asia/Kamchatka',
  'Asia/Karachi',
  'Asia/Kashgar',
  'Asia/Kathmandu',
  'Asia/Katmandu',
  'Asia/Khandyga',
  'Asia/Kolkata',
  'Asia/Krasnoyarsk',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Asia/Kuwait',
  'Asia/Macao',
  'Asia/Macau',
  'Asia/Magadan',
  'Asia/Makassar',
  'Asia/Manila',
  'Asia/Muscat',
  'Asia/Nicosia',
  'Asia/Novokuznetsk',
  'Asia/Novosibirsk',
  'Asia/Omsk',
  'Asia/Oral',
  'Asia/Phnom_Penh',
  'Asia/Pontianak',
  'Asia/Pyongyang',
  'Asia/Qatar',
  'Asia/Qostanay',
  'Asia/Qyzylorda',
  'Asia/Rangoon',
  'Asia/Riyadh',
  'Asia/Saigon',
  'Asia/Sakhalin',
  'Asia/Samarkand',
  'Asia/Seoul',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Srednekolymsk',
  'Asia/Taipei',
  'Asia/Tashkent',
  'Asia/Tbilisi',
  'Asia/Tehran',
  'Asia/Tel_Aviv',
  'Asia/Thimbu',
  'Asia/Thimphu',
  'Asia/Tokyo',
  'Asia/Tomsk',
  'Asia/Ujung_Pandang',
  'Asia/Ulaanbaatar',
  'Asia/Ulan_Bator',
  'Asia/Urumqi',
  'Asia/Ust-Nera',
  'Asia/Vientiane',
  'Asia/Vladivostok',
  'Asia/Yakutsk',
  'Asia/Yangon',
  'Asia/Yekaterinburg',
  'Asia/Yerevan',
  'Atlantic/Azores',
  'Atlantic/Bermuda',
  'Atlantic/Canary',
  'Atlantic/Cape_Verde',
  'Atlantic/Faeroe',
  'Atlantic/Faroe',
  'Atlantic/Jan_Mayen',
  'Atlantic/Madeira',
  'Atlantic/Reykjavik',
  'Atlantic/South_Georgia',
  'Atlantic/St_Helena',
  'Atlantic/Stanley',
  'Australia/ACT',
  'Australia/Adelaide',
  'Australia/Brisbane',
  'Australia/Broken_Hill',
  'Australia/Canberra',
  'Australia/Currie',
  'Australia/Darwin',
  'Australia/Eucla',
  'Australia/Hobart',
  'Australia/LHI',
  'Australia/Lindeman',
  'Australia/Lord_Howe',
  'Australia/Melbourne',
  'Australia/NSW',
  'Australia/North',
  'Australia/Perth',
  'Australia/Queensland',
  'Australia/South',
  'Australia/Sydney',
  'Australia/Tasmania',
  'Australia/Victoria',
  'Australia/West',
  'Australia/Yancowinna',
  'Brazil/Acre',
  'Brazil/DeNoronha',
  'Brazil/East',
  'Brazil/West',
  'CET',
  'CST6CDT',
  'Canada/Atlantic',
  'Canada/Central',
  'Canada/Eastern',
  'Canada/Mountain',
  'Canada/Newfoundland',
  'Canada/Pacific',
  'Canada/Saskatchewan',
  'Canada/Yukon',
  'Chile/Continental',
  'Chile/EasterIsland',
  'Cuba',
  'EET',
  'EST',
  'EST5EDT',
  'Egypt',
  'Eire',
  'Etc/GMT',
  'Etc/GMT+0',
  'Etc/GMT+1',
  'Etc/GMT+10',
  'Etc/GMT+11',
  'Etc/GMT+12',
  'Etc/GMT+2',
  'Etc/GMT+3',
  'Etc/GMT+4',
  'Etc/GMT+5',
  'Etc/GMT+6',
  'Etc/GMT+7',
  'Etc/GMT+8',
  'Etc/GMT+9',
  'Etc/GMT-0',
  'Etc/GMT-1',
  'Etc/GMT-10',
  'Etc/GMT-11',
  'Etc/GMT-12',
  'Etc/GMT-13',
  'Etc/GMT-14',
  'Etc/GMT-2',
  'Etc/GMT-3',
  'Etc/GMT-4',
  'Etc/GMT-5',
  'Etc/GMT-6',
  'Etc/GMT-7',
  'Etc/GMT-8',
  'Etc/GMT-9',
  'Etc/GMT0',
  'Etc/Greenwich',
  'Etc/UCT',
  'Etc/UTC',
  'Etc/Universal',
  'Etc/Zulu',
  'Europe/Amsterdam',
  'Europe/Andorra',
  'Europe/Astrakhan',
  'Europe/Athens',
  'Europe/Belfast',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Europe/Bratislava',
  'Europe/Brussels',
  'Europe/Bucharest',
  'Europe/Budapest',
  'Europe/Busingen',
  'Europe/Chisinau',
  'Europe/Copenhagen',
  'Europe/Dublin',
  'Europe/Gibraltar',
  'Europe/Guernsey',
  'Europe/Helsinki',
  'Europe/Isle_of_Man',
  'Europe/Istanbul',
  'Europe/Jersey',
  'Europe/Kaliningrad',
  'Europe/Kiev',
  'Europe/Kirov',
  'Europe/Lisbon',
  'Europe/Ljubljana',
  'Europe/London',
  'Europe/Luxembourg',
  'Europe/Madrid',
  'Europe/Malta',
  'Europe/Mariehamn',
  'Europe/Minsk',
  'Europe/Monaco',
  'Europe/Moscow',
  'Europe/Nicosia',
  'Europe/Oslo',
  'Europe/Paris',
  'Europe/Podgorica',
  'Europe/Prague',
  'Europe/Riga',
  'Europe/Rome',
  'Europe/Samara',
  'Europe/San_Marino',
  'Europe/Sarajevo',
  'Europe/Saratov',
  'Europe/Simferopol',
  'Europe/Skopje',
  'Europe/Sofia',
  'Europe/Stockholm',
  'Europe/Tallinn',
  'Europe/Tirane',
  'Europe/Tiraspol',
  'Europe/Ulyanovsk',
  'Europe/Uzhgorod',
  'Europe/Vaduz',
  'Europe/Vatican',
  'Europe/Vienna',
  'Europe/Vilnius',
  'Europe/Volgograd',
  'Europe/Warsaw',
  'Europe/Zagreb',
  'Europe/Zaporozhye',
  'Europe/Zurich',
  'GB',
  'GB-Eire',
  'GMT',
  'GMT+0',
  'GMT-0',
  'GMT0',
  'Greenwich',
  'HST',
  'Hongkong',
  'Iceland',
  'Indian/Antananarivo',
  'Indian/Chagos',
  'Indian/Christmas',
  'Indian/Cocos',
  'Indian/Comoro',
  'Indian/Kerguelen',
  'Indian/Mahe',
  'Indian/Maldives',
  'Indian/Mauritius',
  'Indian/Mayotte',
  'Indian/Reunion',
  'Iran',
  'Israel',
  'Jamaica',
  'Japan',
  'Kwajalein',
  'Libya',
  'MET',
  'MST',
  'MST7MDT',
  'Mexico/BajaNorte',
  'Mexico/BajaSur',
  'Mexico/General',
  'NZ',
  'NZ-CHAT',
  'Navajo',
  'PRC',
  'PST8PDT',
  'Pacific/Apia',
  'Pacific/Auckland',
  'Pacific/Bougainville',
  'Pacific/Chatham',
  'Pacific/Chuuk',
  'Pacific/Easter',
  'Pacific/Efate',
  'Pacific/Enderbury',
  'Pacific/Fakaofo',
  'Pacific/Fiji',
  'Pacific/Funafuti',
  'Pacific/Galapagos',
  'Pacific/Gambier',
  'Pacific/Guadalcanal',
  'Pacific/Guam',
  'Pacific/Honolulu',
  'Pacific/Johnston',
  'Pacific/Kiritimati',
  'Pacific/Kosrae',
  'Pacific/Kwajalein',
  'Pacific/Majuro',
  'Pacific/Marquesas',
  'Pacific/Midway',
  'Pacific/Nauru',
  'Pacific/Niue',
  'Pacific/Norfolk',
  'Pacific/Noumea',
  'Pacific/Pago_Pago',
  'Pacific/Palau',
  'Pacific/Pitcairn',
  'Pacific/Pohnpei',
  'Pacific/Ponape',
  'Pacific/Port_Moresby',
  'Pacific/Rarotonga',
  'Pacific/Saipan',
  'Pacific/Samoa',
  'Pacific/Tahiti',
  'Pacific/Tarawa',
  'Pacific/Tongatapu',
  'Pacific/Truk',
  'Pacific/Wake',
  'Pacific/Wallis',
  'Pacific/Yap',
  'Poland',
  'Portugal',
  'ROC',
  'ROK',
  'Singapore',
  'Turkey',
  'UCT',
  'US/Alaska',
  'US/Aleutian',
  'US/Arizona',
  'US/Central',
  'US/East-Indiana',
  'US/Eastern',
  'US/Hawaii',
  'US/Indiana-Starke',
  'US/Michigan',
  'US/Mountain',
  'US/Pacific',
  'US/Pacific-New',
  'US/Samoa',
  'UTC',
  'Universal',
  'W-SU',
  'WET',
  'Zulu',
];

export const IMAGE_BLEND_OPTIONS = [
  { label: 'None', value: '' },
  { label: 'Multiply', value: 'multiply' },
  { label: 'Screen', value: 'screen' },
  { label: 'Overlay', value: 'overlay' },
  { label: 'Darken', value: 'darken' },
  { label: 'Lighten', value: 'lighten' },
  { label: 'Color Dodge', value: 'color-dodge' },
  { label: 'Color Burn', value: 'color-burn' },
  { label: 'Hard Light', value: 'hard-light' },
  { label: 'Soft Light', value: 'soft light' },
  { label: 'Difference', value: 'difference' },
  { label: 'Exclusion', value: 'exclusion' },
  { label: 'Hue', value: 'hue' },
  { label: 'Saturation', value: 'saturation' },
  { label: 'Color', value: 'color' },
  { label: 'Luminosity', value: 'luminosity' },
];

export const ORDER_STATUS_FILTER_OPTIONS = [
  {
    label: <Badget color="#0A497B" label="All" />,
    value: '',
  },
  {
    label: <Badget color="#F1C232" label="Pending" />,
    value: JSON.stringify({ orderStatus: OrderStatus.PENDING }),
  },
  {
    label: <Badget color="#99DBF3" label="In Progress" />,
    value: JSON.stringify({ orderStatus: OrderStatus.IN_PROGRESS }),
  },
  {
    label: <Badget color="#33BD00" label="Completed" />,
    value: JSON.stringify({ orderStatus: OrderStatus.COMPLETED }),
  },
  {
    label: <Badget color="#ECF399" label="Disputed" />,
    value: JSON.stringify({ orderStatus: OrderStatus.DISPUTE }),
  },
  {
    label: <Badget color="#C2C2C2" label="Canceled" />,
    value: JSON.stringify({ orderStatus: OrderStatus.CANCELED }),
  },
  {
    label: <Badget color="#ff8585" label="Refunded" />,
    value: JSON.stringify({ orderStatus: OrderStatus.REFUNDED }),
  },
];
export const ORDER_STATUS_FILTER_OPTIONS_OBJ = {
  '': { label: 'All', value: '' },
  [JSON.stringify({ orderStatus: OrderStatus.PENDING })]: {
    label: 'Pending',
    value: JSON.stringify({ orderStatus: OrderStatus.PENDING }),
  },
  [JSON.stringify({ orderStatus: OrderStatus.IN_PROGRESS })]: {
    label: 'In Progress',
    value: JSON.stringify({ orderStatus: OrderStatus.IN_PROGRESS }),
  },
  [JSON.stringify({ orderStatus: OrderStatus.COMPLETED })]: {
    label: 'Completed',
    value: JSON.stringify({ orderStatus: OrderStatus.COMPLETED }),
  },
  [JSON.stringify({ orderStatus: OrderStatus.DISPUTE })]: {
    label: 'Disputed',
    value: JSON.stringify({ orderStatus: OrderStatus.DISPUTE }),
  },
  [JSON.stringify({ orderStatus: OrderStatus.CANCELED })]: {
    label: 'Canceled',
    value: JSON.stringify({ orderStatus: OrderStatus.CANCELED }),
  },
  [JSON.stringify({ orderStatus: OrderStatus.REFUNDED })]: {
    label: 'Refunded',
    value: JSON.stringify({ orderStatus: OrderStatus.REFUNDED }),
  },
};

export const SUPPORT_TICKETS_STATUS_OPTIONS = [
  {
    label: 'All',
    value: '',
  },
  {
    label: 'Open',
    value: SupportTicketStatus.OPEN,
  },
  {
    label: 'Closed',
    value: SupportTicketStatus.CLOSE,
  },
];

export const SOCIAL_PLATFORM_OPTIONS = [
  {
    label: 'Facebook',
    value: SocialPlatforms.FACEBOOK,
  },
  {
    label: 'Instagram',
    value: SocialPlatforms.INSTAGRAM,
  },
  {
    label: 'Twitter',
    value: SocialPlatforms.TWITTER,
  },
  {
    label: 'Youtube',
    value: SocialPlatforms.YOUTUBE,
  },
  {
    label: 'Tiktok',
    value: SocialPlatforms.TIKTOK,
  },
  {
    label: 'OnlyFans',
    value: SocialPlatforms.ONLYFANS,
  },
  {
    label: 'Snapchat',
    value: SocialPlatforms.SNAPCHAT,
  },
];

export const ScheduledMessagingViews = [
  'listing',
  'edit',
  'add',
  'addPost',
  'editPost',
] as const;
export const SocialIcons: any = {
  snapchat: '/assets/images/snapchat.svg',
  facebook: '/assets/images/icon-fb.jpg',
  youtube: '/assets/images/Youtube-logo.png',
  twitter: '/assets/images/twitter.jpg',
  tiktok: '/assets/images/tiktok.png',
  instagram: '/assets/images/instagram-icon.svg',
};
/*
  post: [
    '150xSCALEXsmobileX50',
    '615xSCALEXmobileX80',
    '1920xSCALEXdesktopX80',
  ],
  */
export const ImagesScreenSizes = {
  profile: [
    '64x64XsmobileX50X0',
    '163x163XmobileX80X0',
    '312x312XdesktopX80X0',
  ],
  profileCover: ['770x420XmobileX80X0', '1920x1080XdesktopX80X0'],

  chat: [
    '163x163XsmobileX70X0',
    '358x358XmobileX80X0',
    '1920x1080XdesktopX80X0',
    '358x358XbdesktopX10X100',
  ],
  scheduleChat: [
    '163x163XsmobileX70X0',
    '358x358XmobileX80X0',
    '1920x1080XdesktopX80X0',
    '358x358XbdesktopX10X100',
  ],
  schedulePost: [
    '163x163XsmobileX70X0',
    '615xSCALEXmobileX80X0',
    '1920xSCALEXdesktopX80X0',
    '615xSCALEXbdesktopX10X100',
  ],
  post: [
    '163x163XsmobileX70X0',
    '615xSCALEXmobileX80X0',
    '1920xSCALEXdesktopX80X0',
    '615xSCALEXbdesktopX10X100',
  ],
  popThumb: ['64x64XmobileX60X0'],
  promotionalMedia: ['770x420XmobileX80X0', '1920x1080XdesktopX80X0'],
  themeBackgroundImage: [
    '160x238XsmobileX80X0',
    '960x540XmobileX80X0',
    '1920x1080XdesktopX80X0',
  ],
  // '320x320' = '320x320',
  // '360x360' = '360x360',
  // '163x163' = '163x163',
  // '64x64' = '64x64',
  // '480x220' = '480x220',
  // '615x347' = '615x347',
  // '900x600' = '900x600',
  // '1920x1080' = '1920x1080',
  // '960x540' = '1920x1080',
};

export const LOGS_EVENTS = {
  publicpageView: 'public_profile_visit',
  homepageSignup: ' homepage_signup',
  membersShipSignup: 'membership_signup:',
  cart_step: 'cart_step',
  phone_added: 'phone_added',
};
export enum ServiceType {
  SHOUTOUT = 'shoutout',
  ADVERTISE = 'advertise',
  PAYMA = 'payma',
  POPLIVE = 'poplive',
  ADDITIONAL_SERVICES = 'additional-services',
  DIGITAL_DOWNLOADS = 'digital-download',
  CHAT_SUBSCRIPTION = 'chat-subscription',
}
export const SERVICES_CART_STEPS: Record<string, any> = {
  shoutout: 3,
  advertise: 3,
  'chat-subscription': 2,
  payma: 3,
  poplive: 3,
  'additional-services': 3,
  'digital-download': 3,
};
export const LOGS_ENVIRONMENTS = {
  development: 'dev-selfiepop',
  production: 'selfiepop',
};
export const GetPopIcon = ({
  type,
  ...rest
}: {
  type?: ServiceType | string;
  primaryColor?: string;
  secondaryColor?: string;
}): any => {
  switch (type) {
    case SocialPlatforms.INSTAGRAM:
      return <LogoInstagram {...rest} />;
    case SocialPlatforms.FACEBOOK:
      return <LogoFacebook {...rest} />;
    case SocialPlatforms.TWITTER:
      return <LogoTwitter {...rest} />;
    case SocialPlatforms.ONLYFANS:
      return <LogoOnlyFans {...rest} />;
    case SocialPlatforms.SNAPCHAT:
      return <LogoSnapChat {...rest} />;
    case SocialPlatforms.YOUTUBE:
      return <LogoYoutube {...rest} />;
    case SocialPlatforms.TIKTOK:
      return <LogoTikTok {...rest} />;
    case ServiceType.SHOUTOUT:
      return <Shoutout {...rest} />;
    case ServiceType.PAYMA:
      return <Payma {...rest} />;

    case ServiceType.DIGITAL_DOWNLOADS:
      return <DigitalDownload {...rest} />;
    case ServiceType.ADVERTISE:
      return <Advertise {...rest} />;
    case ServiceType.POPLIVE:
      return <PopLive {...rest} />;
    case ServiceType.ADDITIONAL_SERVICES:
      return <CustomServices {...rest} />;
    case ServiceType.CHAT_SUBSCRIPTION:
      return <PopChat {...rest} />;
    default:
      return <PopSnap {...rest} />;
  }
};
export const getStatusIcon = (status: string) => {
  switch (status) {
    case 'pending':
      return <PendingStatus />;
    case 'declined':
      return <DeclinedStatus />;
    case 'canceled':
      return <CrossIcon />;
    case 'active':
      return <TickIcon />;
    default:
      return null;
  }
};
export const getOrderStatusIcon = (status: string) => {
  switch (status) {
    case 'pending':
      return <PendingStatus />;
    case 'declined':
      return <DeclinedStatus />;
    case 'canceled':
      return <CrossIcon />;
    case 'completed':
      return <TickIcon />;
    case 'in progress':
      return <TickIcon />;
    default:
      return null;
  }
};
export const ExtraOrderTypes = {
  tip: 'Tip',
  message_unlock: 'Message_Unlock',
  post_unlock: 'Post_Unlock',
};
export const IDVerificationStatuses = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
  processing: 'processing',
};
export const defaultImage = '/assets/images/defaultPlaceholder.svg';
export const defaultImagePlaceholder = '/assets/images/svg/logo.svg';
export const FILE_MIME_TYPE = [
  'image/heif',
  'image/heic',
  'image/heif-sequence',
  'image/heic-sequence',
];
export const InnerCircle = {
  'Subscription Renew': 'Subscription Renew',
  'Time Extend': 'Time Extend',
  message: 'Message',
  'Pay To View': 'Pay To View',
  'Post Tip': 'Post Tip',
  Membership: 'Membership',
};

export const MEDIA_UPLOAD_STATUSES = {
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  IN_PROGRESS: 'IN_PROGRESS',
  ENCODING: 'ENCODING',
  CANCELLED: 'CANCELLED',
} as const;

export const HIDE_WITHDRAWAL: Record<string, string> = {
  '633a42b1ab00040021877ff1': '633a42b1ab00040021877ff1',
};
export const USERCHARGEBACKMESSAGE =
  'This account has open chargebacks. If you think this is a mistake/error please contact the administration';
export const CARDERRORREASONS = {
  SELLER_DEACTIVATE: 'SELLER_DEACTIVATE',
  SELLER_STOP_SELLING: 'SELLER_STOP_SELLING',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  BUYER_PURCHASES_OFF: 'BUYER_PURCHASES_OFF',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_EXPIRED: 'CARD_EXPIRED',
  '3D_CARD': '3D_CARD',
  CARD_DECLINE: 'CARD_DECLINE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
};
